### PR TITLE
Lin contributions

### PR DESCRIPTION
**Pull request by petroskayange**

### CODE REVIEW

**Comment by ntumbuka** [comment]
@petroskayange you want this merged into development?

**Comment by petroskayange** [comment]
> @petroskayange you want this merged into development?

yes

**Comment by ntumbuka** [comment]
Okay... Then change the target branch to development. We merged everything into development and made a release last week. Also you need to resolved the conflicts you have.

**Comment by ntumbuka** [comment]
Got a report that the registrations report is not working after updating in some sites, did you modify it at some point?

**Comment by petroskayange** [comment]
No we didn't modify it but we will look at it

**Comment by petroskayange** [comment]
> Okay... Then change the target branch to development. We merged everything into development and made a release last week. Also you need to resolved the conflicts you have.

okay i will do that

**Pull request closed without merging**
