### PR TITLE
added new drug TD for ANC

### PR DESCRIPTION
**Pull request by Skipper-116**
TTV has been retired.

### CODE REVIEW

**Review by andie23 — CHANGES_REQUESTED** [review]
ANC Cohort has direct name reference to TTV drug name. This will affect reporting with the new TD drug.

See services/anc_service/reports/cohort_builder.rb

**Comment by andie23** [comment]
See line number 604

**Comment by andie23** [comment]
Also check

patient_visit_label.rb
patients_engine.rb

**Comment by Skipper-116** [comment]
> 

There is another PR dealing with the mentioned files...  @andie23

**Comment by andie23** [comment]
Only saw the workflow and this one

**Comment by andie23** [comment]
If possible combine them because they are similar. I did the same approach on the frontend

**Review by andie23 — CHANGES_REQUESTED** [review]
Anc workflow engine is crashing with this error: "#<NoMethodError: undefined method `id' for nil:NilClass>"

You made big changes in this pull request which is making reviewing the core changes difficult and has added bugs. I suggest you make none TD modifications in a separate pull request.

**Pull request closed without merging**
