### PR TITLE
LIN work

### PR DESCRIPTION
**Pull request by petroskayange**

### CODE REVIEW

**Comment by ntumbuka** [comment]
You are supposed to target branch `lin-contributions`. That's where all the changes you previously made are. Just add the metadata and issue a pull request targeting that branch.

**Comment by ntumbuka** [comment]
https://github.com/HISMalawi/BHT-EMR-API/tree/lin-contributions

**Comment by petroskayange** [comment]
Noted

**Comment by ntumbuka** [comment]
Duplicate of #41

**Pull request closed without merging**
