### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by petroskayange**

### CODE REVIEW

**Comment by ntumbuka** [comment]
This pull request has conflicts too and is targeting the wrong branch. And what of the other pull request you have open, are the changes the same as what we have in this one?

**Comment by ntumbuka** [comment]
Can you resolve these today? Want to make a release and push it to the devops team by the end of today.

**Comment by ntumbuka** [comment]
I changed the base branch to `lin-contributions`, it has no conflicts with that branch. Should I merge this?

**Comment by petroskayange** [comment]
i checked the lin-contributions brach and the only problem is that it have
the old openmrs_metadata

**Comment by petroskayange** [comment]
this was a mistake

**Pull request merged**
